### ISSUE TITLE
Failing test suite

### ISSUE THREAD

**Issue by suhail-singh** [anametologin/krohnkite#26]
**Symptom**
When you invoke the `test` target in the Makefile, it results in the following
error:

```
$> make test
sed -i 's/"version": [^,]*/"version": "0.9.5"/' package.json
npm test

> krohnkite@0.9.5 test
> mocha 'test/*.spec.js'


 Exception during run: TypeError: K.TileLayout is not a constructor
    at Suite.<anonymous> (/path/to/krohnkite/test/tilelayout.spec.js:26:18)
    at Object.create (/path/to/krohnkite/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/path/to/krohnkite/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.<anonymous> (/path/to/krohnkite/test/tilelayout.spec.js:25:3)
    at Object.create (/path/to/krohnkite/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/path/to/krohnkite/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/path/to/krohnkite/test/tilelayout.spec.js:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:428:15)
    at async formattedImport (/path/to/krohnkite/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async exports.requireOrImport (/path/to/krohnkite/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async exports.loadFilesAsync (/path/to/krohnkite/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/path/to/krohnkite/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/path/to/krohnkite/node_modules/mocha/lib/cli/run.js:370:5)
make: *** [Makefile:32: test] Error 1
```

**How to Reproduce**
1. Clone the git repository
2. Invoke `make package` followed by `make test`
3. See error

**Expected behavior**
The test suite should successfully execute.

**Environment**
 - Distro: OpenSUSE Tumbleweed
 - KWin version: 6.0.5
 - Krohnkite version: `bcabc63`
 - List of KWin scripts in use: None

**Notes**
N/A

**Comment by anametologin** [comment]
I removed the test suite until it became workable.
